### ISSUE TITLE
Need help in understanding performance

### ISSUE THREAD

**Issue by xtroncode** [DaniilSokolyuk/NodeReact.NET#6]
Hi,
We were planning to move our dotnet core application that renders react on the server using ReactJS.Net to linux, for which we switched from using JavaScriptEngineSwitcher.V8 to JavaScriptEngineSwitcher.ChakraCore but were facing [some issues](https://github.com/Taritsyn/JavaScriptEngineSwitcher/issues/88) with ChakraCore. 

So as per @Taritsyn 's [suggestion](https://github.com/Taritsyn/JavaScriptEngineSwitcher/issues/88#issuecomment-700844044) We tried out JavaScriptEngineSwitcher.Node . While JavaScriptEngineSwitcher.Node is working fine on linux, the performance when compared to JavaScriptEngineSwitcher.V8 is not good  (p50 of ~90ms on V8 vs p50 of ~160ms on Node) for rendering our webpages.

We are unable to use NodeReact.NET due to #5 . 

As per [this](https://github.com/JeringTech/Javascript.NodeJS/issues/83)  the above observation is correct but the benchmarks provided in NodeReact.NET prove otherwise that better performance can be achieved with Node.

I would like to understand why NodeReact.NET has better performance than ReactJS.Net + JavaScriptEngineSwitcher.Node. Is it because of using workerpool ? or something else.

Thanks.

**Comment by DaniilSokolyuk** [comment]
@xtroncode Hi, sorry for the late reply, NodeReact.NET has better performance because it fully async and managed thread can do other work and not wait for the render, also i am reuse allocated memory which causes much fewer garbage collections. Also it uses node.js (out of process) with [worker threads](https://nodejs.org/api/worker_threads.html), rendering is cpu bound operation and it helps

**Comment by DaniilSokolyuk** [comment]
I will do #5 when i have vacation. But when using render functions, performance can drop significantly because it will require much more allocation

**Comment by xtroncode** [comment]
Hi @DaniilSokolyuk , Thanks for the reply. 
We have already started using JavaScriptEngineSwitcher.Node and are able to get an equivalent performance to V8 . The metrics metioned in my question are incorrect, I had later figured out an issue in my environment which was causing high render times.
Thanks again.

**Comment by DaniilSokolyuk** [comment]
@xtroncode main problem in ReactJS.NET +JavaScriptEngineSwitcher.Node is not performance, main problem is sync call JavaScriptEngineSwitcher.Node and threadpool starvation
